### ISSUE TITLE
sea ice error for ultra-low resolution run

### ISSUE THREAD

**Issue by wagmanbe** [sandialabs/CLDERA-E3SM#2]
Trying to run an ultra-low resolution piControl case, I get the following error in ice.log which crashes the run 
` seaice_init: Initialize sea-ice model
  Initialize mesh...
CRITICAL ERROR: rescale_mesh: inconsistent radii: sphere_radius: 6371230.00000000, earthRadius: 6371229.00000000
`

[E3SM runscript](https://gitlab-ex.sandia.gov/cldera/simulated-pathways/-/blob/master/E3SM_runscripts/WCYCL1850/debug/run.v2.ULR.piControl_ne4pg2_oQU480.sh)

**Comment by ikalash** [comment]
Hmmm...  @karapeterson did you encounter this when you were first setting up the ULR runs for your project using v1?

@wagmanbe : how about MLR?  Does that one exhibit a similar error?

**Comment by karapeterson** [comment]
@wagmanbe and @ikalash - I vaguely remember some runs exhibiting a similar error when were getting the v1 ultra-low resolution going. I can't seem to find any notes on it yet, but will look back more carefully and see what I can find out.

**Comment by wagmanbe** [comment]
Thanks @karapeterson @ikalash. It seems like this grid incompatibility problem has also popped up and been solved in the past by using an ICG grid (see this issue from 2018 [https://github.com/E3SM-Project/E3SM/issues/1833](url). ) I tried the two other ne4 grids for an allactive configuration and they failed too, but will keep working on it.

**Comment by karapeterson** [comment]
Based on the E3SM issue you found @wagmanbe the error seems to be associated with using an invalid compset. There is a warning that the sea ice and ocean are trying to find initialization files:

WARNING: The specified compset is requesting seaice ICs spunup from a G-case
         But no file available for this grid.

So I tried to run with a different compset using: COMPSET="WCYCL1850NS"

The nomenclature seems to have changed from v1 to v2 and according to the file
E3SM/code/v2.0.0/cime_config/allactive/config_compsets.xml
this compset uses no spinup for the ice and ocean.  (I think previously the "WCYCL1850" didn't include spinup for the ice and ocean.) Running this compset seemed to work. 

Also, thanks @wagmanbe for changing the file permissions for the input data! There is one more that would be good to fix when you have time: /projects/ccsm/inputdata/rof/mosart/MOSART_Global_2deg_antarctica_flowing_to_north_c09162020.nc

**Comment by wagmanbe** [comment]
Thank you, @karapeterson! I will confirm running that compset works and then close the issue. I opened the permissions to /projects/ccsm/inputdata/rof/mosart/MOSART_Global_2deg_antarctica_flowing_to_north_c09162020.nc
