### ISSUE TITLE
need fsurdat file for ne16pg2 PI-CTRL case

### ISSUE THREAD

**Issue by wagmanbe** [sandialabs/CLDERA-E3SM#3]
Missing surface data file for ne16pg2 PI-CTRL case, causing crash. This is a surfdata file. For ne4pg2 we use fsurdat='/projects/ccsm/inputdata/lnd/clm2/surfdata_map/surfdata_ne4pg2_simyr1850_c210722.nc'. No such file exists for ne16pg2 and we will have to make our own. 
[Runscript](https://gitlab-ex.sandia.gov/cldera/simulated-pathways/-/blob/master/E3SM_runscripts/WCYCL1850/debug/run.v2.ULR.piControl_ne16pg2_r05_oQU240.sh)

**Comment by brhillman** [comment]
@wagmanbe I actually don't think this is needed. In your runscript, you're using the r05 land grid, which already has a fsurday file associated with it. I actually don't get any failure when running your runscript, tweaked a bit for settings on a different machine. Perhaps `check_input_data` just is not correctly downloading the needed file on the machine you're using?

**Comment by wagmanbe** [comment]
@brhillman Thank you, the [(slightly updated) runscript](https://gitlab-ex.sandia.gov/cldera/simulated-pathways/-/blob/master/E3SM_runscripts/WCYCL1850/run.v2.ULR.piControl_ne16pg2_r05_oQU240.sh) is now running on Sandia HPC. I can't be sure why it didn't run before--perhaps I attached the wrong version of the runscript for this particular issue. 
As you point out the ne16pg2_r05_oQU240 configuration is way too high-resolution land for our purposes, but it's the only configuration for coupled ne16. Per our discussion if you could create a ne16_ne16_oQU240 configuration, that would be the best for us going forward. I will create a new "issue" for that and tag you.
